// filters
export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_FILTERS = 'SET_FILTERS';
// journal
export const ADD_ENTRY = 'ADD_ENTRY';
export const EDIT_ENTRY = 'EDIT_ENTRY';
export const GET_JOURNAL = 'GET_JOURNAL';
export const REMOVE_ENTRY = 'REMOVE_ENTRY';
export const REQUEST_JOURNAL = 'REQUEST_JOURNAL';
export const REQUEST_JOURNAL_FAILURE = 'REQUEST_JOURNAL_FAILURE';
export const REQUEST_JOURNAL_SUCCESS = 'REQUEST_JOURNAL_SUCCESS';
// logs
export const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
export const ADD_FOOD = 'ADD_FOOD';
export const ADD_MOVEMENT = 'ADD_MOVEMENT';
export const ADD_NSAID = 'ADD_NSAID';
export const ADD_PRACTITIONER = 'ADD_PRACTITIONER';
export const ADD_SUPPLEMENT = 'ADD_SUPPLEMENT';
export const GET_LOGS = 'GET_LOGS';
export const REMOVE_SUPPLEMENT = 'REMOVE_SUPPLEMENT';
export const REQUEST_LOGS = 'REQUEST_LOGS';
export const REQUEST_LOGS_FAILURE = 'REQUEST_LOGS_FAILURE';
export const REQUEST_LOGS_SUCCESS = 'REQUEST_LOGS_SUCCESS';
// profile
export const ADD_PROFILE = 'ADD_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const REQUEST_PROFILE = 'REQUEST_PROFILE';
export const REQUEST_PROFILE_FAILURE = 'REQUEST_PROFILE_FAILURE';
export const REQUEST_PROFILE_SUCCESS = 'REQUEST_PROFILE_SUCCESS';
