// filters
export const RESET_FILTERS = 'RESET_FILTERS';
export const SET_FILTERS = 'SET_FILTERS';

// journal
export const ADD_ENTRY_REQUEST = 'ADD_ENTRY_REQUEST';
export const ADD_ENTRY_SUCCESS = 'ADD_ENTRY_SUCCESS';
export const ADD_ENTRY_FAILURE = 'ADD_ENTRY_FAILURE';
export const EDIT_ENTRY_REQUEST = 'EDIT_ENTRY_REQUEST';
export const EDIT_ENTRY_SUCCESS = 'EDIT_ENTRY_SUCCESS';
export const EDIT_ENTRY_FAILURE = 'EDIT_ENTRY_FAILURE';
export const GET_JOURNAL_REQUEST = 'GET_JOURNAL_REQUEST';
export const GET_JOURNAL_SUCCESS = 'GET_JOURNAL_SUCCESS';
export const GET_JOURNAL_FAILURE = 'GET_JOURNAL_FAILURE';
export const REMOVE_ENTRY_REQUEST = 'REMOVE_ENTRY_REQUEST';
export const REMOVE_ENTRY_SUCCESS = 'REMOVE_ENTRY_SUCCESS';
export const REMOVE_ENTRY_FAILURE = 'REMOVE_ENTRY_FAILURE';

// logs
export const ADD_APPOINTMENT_REQUEST = 'ADD_APPOINTMENT_REQUEST';
export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS';
export const ADD_APPOINTMENT_FAILURE = 'ADD_APPOINTMENT_FAILURE';
export const ADD_FOOD_REQUEST = 'ADD_FOOD_REQUEST';
export const ADD_FOOD_SUCCESS = 'ADD_FOOD_SUCCESS';
export const ADD_FOOD_FAILURE = 'ADD_FOOD_FAILURE';
export const ADD_MOVEMENT_REQUEST = 'ADD_MOVEMENT_REQUEST';
export const ADD_MOVEMENT_SUCCESS = 'ADD_MOVEMENT_SUCCESS';
export const ADD_MOVEMENT_FAILURE = 'ADD_MOVEMENT_FAILURE';
export const ADD_NSAID_REQUEST = 'ADD_NSAID_REQUEST';
export const ADD_NSAID_SUCCESS = 'ADD_NSAID_SUCCESS';
export const ADD_NSAID_FAILURE = 'ADD_NSAID_FAILURE';
export const ADD_PRACTITIONER_REQUEST = 'ADD_PRACTITIONER_REQUEST';
export const ADD_PRACTITIONER_SUCCESS = 'ADD_PRACTITIONER_SUCCESS';
export const ADD_PRACTITIONER_FAILURE = 'ADD_PRACTITIONER_FAILURE';
export const ADD_SUPPLEMENT_REQUEST = 'ADD_SUPPLEMENT_REQUEST';
export const ADD_SUPPLEMENT_SUCCESS = 'ADD_SUPPLEMENT_SUCCESS';
export const ADD_SUPPLEMENT_FAILURE = 'ADD_SUPPLEMENT_FAILURE';
export const GET_LOGS_REQUEST = 'GET_LOGS_REQUEST';
export const GET_LOGS_SUCCESS = 'GET_LOGS_SUCCESS';
export const GET_LOGS_FAILURE = 'GET_LOGS_FAILURE';
export const REMOVE_SUPPLEMENT_REQUEST = 'REMOVE_SUPPLEMENT_REQUEST';
export const REMOVE_SUPPLEMENT_SUCCESS = 'REMOVE_SUPPLEMENT_SUCCESS';
export const REMOVE_SUPPLEMENT_FAILURE = 'REMOVE_SUPPLEMENT_FAILURE';

// profile
export const ADD_PROFILE_REQUEST = 'ADD_PROFILE_REQUEST';
export const ADD_PROFILE_SUCCESS = 'ADD_PROFILE_SUCCESS';
export const ADD_PROFILE_FAILURE = 'ADD_PROFILE_FAILURE';
export const GET_PROFILE_REQUEST = 'GET_PROFILE_REQUEST';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';

// user
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
